services:
  db:
    image: postgres:15-alpine
    container_name: diceymio-db
    restart: always
    environment:
      POSTGRES_USER: dot_bd_reseller
      POSTGRES_PASSWORD: dot_bd_reseller
      POSTGRES_DB: diceymio
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
